- name: Add APT key
  apt_key:
    id: "EA312927"
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: mongodb
  apt:
    name: mongodb
  tags: install

- name: start mongodb
  service: name=mongodb state=started
  tags: install

- name: enable mongodb
  service:
    name: mongodb
    enabled: yes
  tags: install
