---
# tasks file for app

- name: Show info
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongodb.conf
    mode: 0644
  notify: restart mongodb
