- name: Update APT Cache
  tags: ruby
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Remove apt lock file
  tags: ruby
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: install packages
  tags: ruby
  apt:
    name: "{{ item }}"
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
