- name: Configure application

  hosts: app
  become: true
  vars:
    db_host: 192.168.10.10 # internal_ip_address_db

  tasks:

    - name: Install git
      apt:
        name: git

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:

    - name: reload puma
      systemd: name=puma state=restarted
