- name: Apt install git
  hosts: app
  tasks:
    - name: Apt install git
      become: yes
      apt:
        name: git

- name: Clone
  hosts: app
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
